# .github/workflows/2-cd-deploy-render.yml
name: 2. CD 一键部署到Render

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: '要部署的镜像标签'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 部署最新镜像到Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          image-url: ghcr.io/huangleikn/devops-poc-app:${{ inputs.image_tag }}
          wait-for-deploy: true

      - name: 部署成功
        run: |
          echo "✅ 部署完成！"
          echo "✅ 服务地址：https://devops-poc-app.onrender.com"